#!/bin/bash
set -e     # to avoid errors being silently ignored

#-------- Gestion des kernels pour les notebooks ------------
# Modification of configuration of the jupyter server to add the notebook environment's bin directory to PATH
mkdir -p ~/.jupyter
cat > ~/.jupyter/jupyter_server_config.py <<'EOF'
import os
os.environ["PATH"] = "/srv/conda/envs/notebook/bin:" + os.environ["PATH"]
EOF

#-------- R kernel and packages ------------
# Gère le kernel R pour cet environnement
R --quiet -e "IRkernel::installspec(prefix='/srv/conda/envs/notebook')" || true

# 1 - Install R packages
# if not available as conda package
# R -e "install.packages('diagram', repos='http://cran.rstudio.com/')"
R -e "install.packages('swirl', repos='http://cran.rstudio.com/')"
R -e "install.packages('knitr', repos='http://cran.rstudio.com/')"
R -e "install.packages('rmarkdown', repos='http://cran.rstudio.com/')"

# 2 - Install R/Bioconductor packages
# if not available as conda package

# First install Bioconductor package manager
# https://bioconductor.org/install/
# R -e "install.packages('BiocManager', repos='http://cran.rstudio.com/')"
# R -e "BiocManager::install()"

# Then install required packages
# Biostrings: Efficient manipulation of biological strings
# https://bioconductor.org/packages/release/bioc/html/Biostrings.html
# R -e "BiocManager::install('Biostrings')"
R -e "BiocManager::install('BiocGenerics')"            # inclut Biostrings, for efficient manipulation of biological strings
R -e "BiocManager::install('GenomicRanges')"
R -e "BiocManager::install('biomaRt')"                 # inclut RSQLite
R -e "BiocManager::install('phyloseq')"
R -e "BiocManager::install('DESeq2')"
R -e "BiocManager::install('org.Mm.eg.db')"
R -e "BiocManager::install('clusterProfiler')"
R -e "BiocManager::install('SummarizedExperiment')"

